application: engineapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /font
  static_dir: static/font
- url: /images
  static_dir: static/images
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
