application: cs399finalproject
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /font
  static_dir: static/font
- url: /images
  static_dir: static/images
- url: /dashboard
  script: main.app
  login: required
- url: /landing
  script: main.app
  login: required
- url: /about
  script: main.app
  login: required
- url: /
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
